# Generated by Django 5.0.1 on 2024-01-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_tag_entry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='date_added',
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entry_images/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes_app.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='notes_app.entry')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
