# Generated by Django 5.0.1 on 2024-02-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
