# Generated by Django 5.0.1 on 2024-02-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='owner',
        ),
    ]
